//@ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 board.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelBase } from '../scene/Demo'

export default function Board(props) {
  const { nodes, materials } = useGLTF(modelBase + '/board.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-5.53, 4.78, -5.44]} rotation={[Math.PI / 2, 0, 2.29]} scale={0.02}>
        <mesh geometry={nodes.Mesh018.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.Mesh018_1.geometry} material={materials.lambert2} />
        <mesh geometry={nodes.Mesh018_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Mesh018_3.geometry} material={materials['lambert1.001']} />
      </group>
    </group>
  )
}

