//@ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./shedTop3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { modelBase } from '../../Demo'

export default function ShedTop3() {
    const { nodes, materials } = useGLTF(modelBase + '/shedTop3.glb')
    return (
        <group dispose={null}>
            <group position={[-18.61, 2.77, -16.96]} rotation={[0, -1.57, 0]} scale={0.23}>
                <mesh geometry={nodes.Object_1.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_10.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_109.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_11.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_110.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_114.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_115.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_12.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_13.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_135.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_136.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_14.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_140.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_141.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_15.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_16.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_161.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_162.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_166.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_167.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_17.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_18.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_187.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_188.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_19.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_192.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_193.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_2.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_20.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_21.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_213.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_214.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_218.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_219.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_22.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_23.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_239.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_24.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_240.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_244.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_245.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_25.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_26.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_265.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_266.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_27.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_270.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_271.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_28.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_29.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_291.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_292.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_296.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_297.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_3.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_30.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_31.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_317.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_318.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_32.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_322.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_323.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_33.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_343.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_344.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_348.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_349.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_36.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_369.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_37.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_370.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_374.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_375.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_38.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_39.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_395.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_396.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_4.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_400.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_401.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_42.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_421.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_422.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_426.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_427.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_43.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_47.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_48.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_5.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_6.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_7.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_8.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_83.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_84.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_88.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_89.geometry} material={materials['/Wood_02']} />
                <mesh geometry={nodes.Object_9.geometry} material={materials['/Wood_02']} />
            </group>
        </group>
    )
}

useGLTF.preload('./resources/SFu/models/shedTop3.glb')
