/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import {
    useGLTF,

} from '@react-three/drei'
import { Object3DProps } from '@react-three/fiber'
import { Group } from 'three'
import { useMyContext } from '../Utils/useMyContext'

import { Button, Modal } from 'antd';


const Tree = (props: Object3DProps) => {
    const group = useRef<Group>(null!)
    const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-lime/model.gltf')
    const { setTutorialModalOpen } = useMyContext();

    return (
        <>
            <group
            ref={group}
            dispose={null}
            {...props}
            >
                <mesh geometry={nodes['tree-lime'].geometry} material={materials.color_main} onClick={(e) => setTutorialModalOpen(true)}/>
            </group>      
        </>
    )
}

export default Tree;

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-lime/model.gltf')