/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 map.glb --transform
*/
//@ts-nocheck

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Map(props) {
  const { nodes, materials } = useGLTF('./resources/map-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bulletin_Board.geometry} material={materials.initialShadingGroup} position={[0.02, 0.02, -0.01]} rotation={[Math.PI / 2, 0, 0]} scale={[1.34, 0.15, 1.34]} />
      {/* <mesh geometry={nodes.Bulletin_Board001.geometry} material={materials.initialShadingGroup} position={[0.07, -0.07, -0.01]} rotation={[Math.PI / 2, 0, 0]} /> */}
      {/* <mesh geometry={nodes.圖釘.geometry} material={materials.initialShadingGroup} position={[0.07, -0.07, -0.01]} rotation={[Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.map.geometry} material={materials.B_02_A} position={[0.02, 2.59, 0.04]} rotation={[Math.PI / 2, 0, 0]} scale={2.16} />
      <mesh geometry={nodes.library.geometry} material={nodes.library.material} position={[0.33, 2.64, 0.51]} rotation={[Math.PI / 2, 0, 0]} scale={0.07} />
    </group>
  )
}

useGLTF.preload('/resources/map-transformed.glb')
