/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
//@ts-nocheck

import React, { useRef } from 'react'
import {
    useGLTF,

} from '@react-three/drei'
import { Object3DProps } from '@react-three/fiber'


export default function Stairs(props: Object3DProps) {
    const group = useRef()
    const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/stairs/model.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.stairs.geometry} material={materials['Stone.034']} rotation={[Math.PI / 2, 0, 0,]} />
        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/stairs/model.gltf')