/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// @ts-nocheck

import React, { useRef, useState } from 'react'
import {
    useGLTF,

} from '@react-three/drei'
import { Object3DProps } from '@react-three/fiber'
import { Group } from 'three'
import { Button, Modal } from 'antd';
import { useMyContext } from '../../../../Utils/useMyContext'


const Tree1 = (props: Object3DProps) => {
    const group = useRef<Group>(null!)
    const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-lime/model.gltf')
    const { setTutorialModalOpen } = useMyContext();

    return (
        <group {...props}>
            <group
                ref={group}
                dispose={null}
                position={[0, 0, 0.5]}
            >
                <mesh geometry={nodes['tree-lime'].geometry} material={materials.color_main} onClick={(e) => setTutorialModalOpen(true)} />
            </group>
        </group>
    )
}

export default Tree1;

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-lime/model.gltf')